name: Generate Brave Adblock
on:
  schedule:
    - cron: '0 * * * *' # Chạy mỗi giờ (không cần tính toán offset timezone)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Fetch and Merge Filters
        run: |
          curl -sL "https://raw.githubusercontent.com/brave/adblock-resources/master/filter_lists/list_catalog.json" | \
          jq -r '.[] | select(.default_enabled == true) | .sources[].url' | \
          xargs curl -sL > brave-adblock.txt
          
      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add brave-adblock.txt
          git commit -m "Auto-update brave-adblock.txt" || exit 0
          git push
